#######################################################################
#COD created by tatemylove                                            #
#Looking for broken and broken plugin? You downloaded the wrong one ;)#
#######################################################################
#General Section (Optional)

#Minimum amount of players to start the game
min-players: 2

#Maximum players allowed in a game
max-players: 10

#Forces the player to join the queue when joining the server
auto-join: false

#Enable or Disable Friendly Fire
friend-fire: false

countdown-time: 20
###########################
#MySQL (Optional) (Required for multi server stat syncing)
MySQL:
  Enabled: false
  Username: user
  Password: password
  Ip: 0.0.0.0
  Database: tatemylove_rocks
############################
#Economy Section (Optional) (Requires my SwiftEconomy plugin, free download from www.spigotmc.org)
SwiftEconomy:
  Enabled: false

  #Amount to give to the winning team/player
  win-amount: 0

  #Amount to give to the losing team/player
  loss-amount: 0

  #Amount to give to a player who dies
  death-amount: 0
############################
#Language Section (Optional)
#Check the 'language.yml' file
############################


#Copyright © 2017 tatemylove. All rights reserved

